Attribute VB_Name = "PublicVariables"
Option Explicit
    
Public usbcommvalue As Range
Public ioMgr       As VisaComLib.ResourceManager
Public instrument  As VisaComLib.FormattedIO488
Public instru      As VisaComLib.FormattedIO488
Public addstdvalue As Range
Public gpib        As VisaComLib.IGpib
Public gpib3458    As VisaComLib.IGpib
Public inst3458    As VisaComLib.FormattedIO488
Public add3458value As Range
Public addCommvalue As Range
Public Initialized3458 As String
Public InitializedCalibrator As String
Public CalibModel As String
Public DMMModel As String
Public shouldContinue As Boolean
Public TerminateClicked As Boolean
Public PassClicked As Boolean
Public FailClicked As Boolean
Public addresses As Variant
Public func         As String
Public funct        As String
Public inst_valueFinal As Double
Public Tab1 As String
Public Tab2 As String
Public Tab3 As String
Public Tab4 As String
Public ATab1 As String
Public ATab2 As String
Public ATab3 As String
Public ATab4 As String
Public WorkOrder As String
Public Accredited As String
Public PathtoWB As String
Public dataSheet As Worksheet
Public InfoDataSheet As Worksheet
Public infoSheet As Worksheet
Public WorkOrderSheet As Worksheet
Public cellAddress As Range
Public ranges As Variant
Public ranges2 As Variant
Public ranges3 As Variant
Public PrevAddress As String
Public PrevTestSect As Integer
Public SameTest As Integer
Public PrevSameTest As Integer
Public OffValueV As Double
Public OffValueU As String
Public OffValueHz As Double
Public OffValueHzU As String
Public offset As Double
Public OffSetU As String
Public Wave As String
Public DR As Integer
Public CalibListed As Boolean
Public FreqUser As Boolean
Public TestSect As Integer
Public Rangelck As String
Public CalibStatus As String
Public Make As String
Public Model As String
Public UnitDesc As String
Public Check As String
Public comp As String
Public duty As Double
Public activeCol As Long
Public inputString As String
Public i As Integer
Public found As Boolean
Public prefix As String
Public ohmString As String
Public numericValue As String
Public tabName As String
Public Skips As Variant
Public stdbyComms As Variant
Public Skipped As Boolean
Public TestSectA As Variant
Public HVImageLoc As String
Public TestPoint As Variant
Public TestPointUnits As Variant
Public TestPointFrequency As Variant
Public TestPointFrequencyUnits As Variant
Public TestPointWave As Variant
Public TestPointOffset As Variant
Public TestPointComp As Variant
Public TestPointDuty As Variant
Public LastCellF As String
Public LastCellG As String
Public LastCellH As String
Public ColNumAF As Integer
Public ColNumAL As Integer
Public ColLetterAF As String
Public ColLetterAL As String


